fix for Django 2 renaming of _format_value()
This fixes #11 -- `AttributeError: 'IntlTelInputWidget' object has no attribute '_format_value'` in recent Django versions.